swagger: '2.0'
info:
  title: MilMove PPTAS API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: milmove-developers@caci.com
  description: >
    The PPTAS API is a RESTful API that enables the Navy's PPTAS system to
    request

    information relating to current moves in progress.


    All endpoints are located at `/prime/pptas/`.
basePath: /prime/pptas
host: primelocal
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
tags:
  - name: moves
paths:
  /moves:
    get:
      summary: listReports
      description: |
        Gets all reports that have been ??approved??
      operationId: listReports
      tags:
        - moves
      produces:
        - application/json
      parameters:
        - in: query
          name: since
          type: string
          format: date-time
          description: >-
            Only return moves updated since this time. Formatted like
            "2021-07-23T18:30:47.116Z"
      responses:
        '200':
          description: >-
            Successfully retrieved moves. A successful fetch might still return
            zero moves.
          schema:
            $ref: '#/definitions/ListReports'
        '401':
          $ref: '#/responses/PermissionDenied'
        '403':
          $ref: '#/responses/PermissionDenied'
        '500':
          $ref: '#/responses/ServerError'
definitions:
  Affiliation:
    type: string
    x-nullable: true
    title: Branch of service
    description: Military branch of service
    enum:
      - ARMY
      - NAVY
      - MARINES
      - AIR_FORCE
      - COAST_GUARD
      - SPACE_FORCE
      - OTHER
    x-display-value:
      ARMY: Army
      NAVY: Navy
      MARINES: Marine Corps
      AIR_FORCE: Air Force
      COAST_GUARD: Coast Guard
      SPACE_FORCE: Space Force
      OTHER: OTHER
  ListReport:
    description: >
      An abbreviated definition for a report, without all the nested information
      (shipments, service items, etc). Used to fetch a list of reports more
      efficiently.
    type: object
    properties:
      ID:
        type: string
        format: uuid
      LastName:
        example: Job
        type: string
      FirstName:
        example: Bob
        type: string
      MiddleInitial:
        example: G
        type: string
      Affiliation:
        $ref: '#/definitions/Affiliation'
      Grade:
        type: string
        x-nullable: true
        title: grade
        enum:
          - E_1
          - E_2
          - E_3
          - E_4
          - E_5
          - E_6
          - E_7
          - E_8
          - E_9
          - E_9_SPECIAL_SENIOR_ENLISTED
          - O_1_ACADEMY_GRADUATE
          - O_2
          - O_3
          - O_4
          - O_5
          - O_6
          - O_7
          - O_8
          - O_9
          - O_10
          - W_1
          - W_2
          - W_3
          - W_4
          - W_5
          - AVIATION_CADET
          - CIVILIAN_EMPLOYEE
          - ACADEMY_CADET
          - MIDSHIPMAN
        x-display-value:
          E_1: E-1
          E_2: E-2
          E_3: E-3
          E_4: E-4
          E_5: E-5
          E_6: E-6
          E_7: E-7
          E_8: E-8
          E_9: E-9
          E_9_SPECIAL_SENIOR_ENLISTED: E-9 (Special Senior Enlisted)
          O_1_ACADEMY_GRADUATE: O-1 or Service Academy Graduate
          O_2: O-2
          O_3: O-3
          O_4: O-4
          O_5: O-5
          O_6: O-6
          O_7: O-7
          O_8: O-8
          O_9: O-9
          O_10: O-10
          W_1: W-1
          W_2: W-2
          W_3: W-3
          W_4: W-4
          W_5: W-5
          AVIATION_CADET: Aviation Cadet
          CIVILIAN_EMPLOYEE: Civilian Employee
          ACADEMY_CADET: Service Academy Cadet
          MIDSHIPMAN: Midshipman
      Edipi:
        example: 1234567890
        type: string
      PhonePrimary:
        example: a@b.com
        type: string
      PhoneSecondary:
        example: a@b.com
        type: string
      EmailPrimary:
        example: 9169876543
        type: string
      EmailSecondary:
        example: 2101234567
        type: string
  ListReports:
    type: array
    items:
      $ref: '#/definitions/ListReport'
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
      - instance
responses:
  PermissionDenied:
    description: The request was denied.
    schema:
      $ref: '#/definitions/ClientError'
  ServerError:
    description: An unexpected error has occurred in the server.
    schema:
      $ref: '#/definitions/ClientError'
