swagger: '2.0'
info:
  title: PPTAS API
  description: This API does things. For more information, see our detailed documentation.
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: milmove-developers@caci.com
host: localhost
schemes:
  - https
tags:
  - name: test
    description: tag to describe test endpoints
  - name: moves
    description: describes all endpoints relating to moves
paths:
  /test/getMovesSince:
    get:
      tags:
        - moves
      summary: summary
      description: summary2
      operationId: movesSince
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              moveSinceDate:
                type: string
                description: moves retrieved since this date
                format: date-time
              numMoves:
                type: string
                description: number of moves to return
      responses:
        '200':
          description: Moves returned sucessfully
          schema:
            $ref: '#/definitions/GetMovesSinceResponse'
        '400':
          $ref: '#/responses/InvalidRequest'
        '401':
          $ref: '#/responses/InvalidRequest'
        '500':
          $ref: '#/responses/ServerError'
definitions:
  MoveStatus:
    type: string
    enum:
      - DRAFT
      - SUBMITTED
      - APPROVED
      - CANCELED
  GBLOC:
    type: string
    enum:
      - AGFM
      - APAT
      - BGAC
      - BGNC
      - BKAS
      - CFMQ
      - CLPK
      - CNNQ
      - DMAT
      - GSAT
      - HAFC
      - HBAT
      - JEAT
      - JENQ
      - KKFA
      - LHNQ
      - LKNQ
      - MAPK
      - MAPS
      - MBFL
      - MLNQ
      - XXXX
  SearchMove:
    type: object
    properties:
      id:
        type: string
        format: uuid
      firstName:
        type: string
        example: John
        x-nullable: true
      lastName:
        type: string
        example: Doe
        x-nullable: true
      dodID:
        type: string
        example: '1234567890'
        x-nullable: true
      status:
        $ref: '#/definitions/MoveStatus'
      locator:
        type: string
      branch:
        type: string
      shipmentsCount:
        type: integer
      originDutyLocationPostalCode:
        format: zip
        type: string
        title: ZIP
        example: '90210'
        pattern: ^(\d{5})$
      destinationDutyLocationPostalCode:
        format: zip
        type: string
        title: ZIP
        example: '90210'
        pattern: ^(\d{5})$
      requestedPickupDate:
        type: string
        format: date
        x-nullable: true
      requestedDeliveryDate:
        type: string
        format: date
        x-nullable: true
      originGBLOC:
        $ref: '#/definitions/GBLOC'
      destinationGBLOC:
        $ref: '#/definitions/GBLOC'
      orderType:
        type: string
  SearchMoves:
    type: array
    items:
      $ref: '#/definitions/SearchMove'
  GetMovesSinceResponse:
    type: object
    properties:
      movesFound:
        $ref: '#/definitions/SearchMoves'
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
      - instance
responses:
  InvalidRequest:
    description: The request was invalid as called.
    schema:
      $ref: '#/definitions/ClientError'
  ServerError:
    description: An unexpected error has occurred in the server.
    schema:
      $ref: '#/definitions/ClientError'
