swagger: '2.0'
info:
  title: MilMove PPTAS API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: milmove-developers@caci.com
  description: |
    All endpoints are located at `/prime/pptas`.
basePath: /prime/pptas
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
tags:
  - name: moves
paths:
  /moves:
    get:
      summary: listMoves
      description: >
        Gets all moves that have been reviewed and approved by the TOO. The
        `since` parameter can be used to filter this

        list down to only the moves that have been updated since the provided
        timestamp. A move will be considered

        updated if the `updatedAt` timestamp on the move or on its orders,
        shipments, service items, or payment

        requests, is later than the provided date and time.


        **WIP**: Include what causes moves to leave this list. Currently, once
        the `availableToPrimeAt` timestamp has

        been set, that move will always appear in this list.
      operationId: listMoves
      tags:
        - moves
      produces:
        - application/json
      parameters:
        - in: query
          name: since
          type: string
          format: date-time
          description: >-
            Only return moves updated since this time. Formatted like
            "2021-07-23T18:30:47.116Z"
      responses:
        '200':
          description: >-
            Successfully retrieved moves. A successful fetch might still return
            zero moves.
          schema:
            $ref: '#/definitions/ListMoves'
        '401':
          $ref: '#/responses/PermissionDenied'
        '403':
          $ref: '#/responses/PermissionDenied'
        '500':
          $ref: '#/responses/ServerError'
definitions:
  Error:
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
    type: object
  ListMove:
    description: >
      An abbreviated definition for a move, without all the nested information
      (shipments, service items, etc). Used to fetch a list of moves more
      efficiently.
    type: object
    properties:
      id:
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
        format: uuid
        type: string
      moveCode:
        type: string
        example: HYXFJF
        readOnly: true
      createdAt:
        format: date-time
        type: string
        readOnly: true
      orderID:
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
        format: uuid
        type: string
      referenceId:
        example: 1001-3456
        type: string
      availableToPrimeAt:
        format: date-time
        type: string
        x-nullable: true
        readOnly: true
      updatedAt:
        format: date-time
        type: string
        readOnly: true
      ppmType:
        type: string
        enum:
          - FULL
          - PARTIAL
      eTag:
        type: string
        readOnly: true
  ListMoves:
    type: array
    items:
      $ref: '#/definitions/ListMove'
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
      - instance
responses:
  InvalidRequest:
    description: The request payload is invalid.
    schema:
      $ref: '#/definitions/ClientError'
  ServerError:
    description: A server error occurred.
    schema:
      $ref: '#/definitions/Error'
  NotImplemented:
    description: The requested feature is still in development.
    schema:
      $ref: '#/definitions/Error'
  PreconditionFailed:
    description: >-
      Precondition failed, likely due to a stale eTag (If-Match). Fetch the
      request again to get the updated eTag value.
    schema:
      $ref: '#/definitions/ClientError'
  PermissionDenied:
    description: The request was denied.
    schema:
      $ref: '#/definitions/ClientError'
