swagger: '2.0'
info:
  title: MilMove PPTAS API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: milmove-developers@caci.com
  description: >
    The PPTAS API is a RESTful API that enables the Navy's PPTAS system to
    request

    information relating to current moves in progress.


    All endpoints are located at `/prime/pptas/`.
basePath: /prime/pptas
host: primelocal
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
tags:
  - name: moves
paths:
  /moves:
    get:
      summary: listReports
      description: |
        Gets all reports that have been ??approved??
      operationId: listReports
      tags:
        - moves
      produces:
        - application/json
      parameters:
        - in: query
          name: since
          type: string
          format: date-time
          description: >-
            Only return moves updated since this time. Formatted like
            "2021-07-23T18:30:47.116Z"
      responses:
        '200':
          description: >-
            Successfully retrieved moves. A successful fetch might still return
            zero moves.
          schema:
            $ref: '#/definitions/ListReports'
        '401':
          $ref: '#/responses/PermissionDenied'
        '403':
          $ref: '#/responses/PermissionDenied'
        '500':
          $ref: '#/responses/ServerError'
definitions:
  Affiliation:
    type: string
    x-nullable: true
    title: Branch of service
    description: Military branch of service
    enum:
      - ARMY
      - NAVY
      - MARINES
      - AIR_FORCE
      - COAST_GUARD
      - SPACE_FORCE
      - OTHER
    x-display-value:
      ARMY: Army
      NAVY: Navy
      MARINES: Marine Corps
      AIR_FORCE: Air Force
      COAST_GUARD: Coast Guard
      SPACE_FORCE: Space Force
      OTHER: OTHER
  Address:
    description: A postal address
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      streetAddress1:
        type: string
        example: 123 Main Ave
        title: Street address 1
      streetAddress2:
        type: string
        example: Apartment 9000
        x-nullable: true
        title: Street address 2
      streetAddress3:
        type: string
        example: Montmârtre
        x-nullable: true
        title: Address Line 3
      city:
        type: string
        example: Anytown
        title: City
      eTag:
        type: string
        readOnly: true
      state:
        title: State
        type: string
        x-display-value:
          AL: AL
          AK: AK
          AR: AR
          AZ: AZ
          CA: CA
          CO: CO
          CT: CT
          DC: DC
          DE: DE
          FL: FL
          GA: GA
          HI: HI
          IA: IA
          ID: ID
          IL: IL
          IN: IN
          KS: KS
          KY: KY
          LA: LA
          MA: MA
          MD: MD
          ME: ME
          MI: MI
          MN: MN
          MO: MO
          MS: MS
          MT: MT
          NC: NC
          ND: ND
          NE: NE
          NH: NH
          NJ: NJ
          NM: NM
          NV: NV
          NY: NY
          OH: OH
          OK: OK
          OR: OR
          PA: PA
          RI: RI
          SC: SC
          SD: SD
          TN: TN
          TX: TX
          UT: UT
          VA: VA
          VT: VT
          WA: WA
          WI: WI
          WV: WV
          WY: WY
        enum:
          - AL
          - AK
          - AR
          - AZ
          - CA
          - CO
          - CT
          - DC
          - DE
          - FL
          - GA
          - HI
          - IA
          - ID
          - IL
          - IN
          - KS
          - KY
          - LA
          - MA
          - MD
          - ME
          - MI
          - MN
          - MO
          - MS
          - MT
          - NC
          - ND
          - NE
          - NH
          - NJ
          - NM
          - NV
          - NY
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VA
          - VT
          - WA
          - WI
          - WV
          - WY
      postalCode:
        type: string
        format: zip
        title: ZIP
        example: '90210'
        pattern: ^(\d{5}([\-]\d{4})?)$
      country:
        type: string
        title: Country
        x-nullable: true
        example: USA
        default: USA
      county:
        type: string
        title: County
        x-nullable: true
        example: LOS ANGELES
    required:
      - streetAddress1
      - city
      - state
      - postalCode
  ListReport:
    description: >
      An abbreviated definition for a report, without all the nested information
      (shipments, service items, etc). Used to fetch a list of reports more
      efficiently.
    type: object
    properties:
      ID:
        type: string
        format: uuid
      FirstName:
        example: Bob
        type: string
      LastName:
        example: Job
        type: string
      MiddleInitial:
        example: G
        type: string
      Affiliation:
        $ref: '#/definitions/Affiliation'
      PayGrade:
        type: string
        x-nullable: true
        title: grade
        enum:
          - E_1
          - E_2
          - E_3
          - E_4
          - E_5
          - E_6
          - E_7
          - E_8
          - E_9
          - E_9_SPECIAL_SENIOR_ENLISTED
          - O_1_ACADEMY_GRADUATE
          - O_2
          - O_3
          - O_4
          - O_5
          - O_6
          - O_7
          - O_8
          - O_9
          - O_10
          - W_1
          - W_2
          - W_3
          - W_4
          - W_5
          - AVIATION_CADET
          - CIVILIAN_EMPLOYEE
          - ACADEMY_CADET
          - MIDSHIPMAN
        x-display-value:
          E_1: E-1
          E_2: E-2
          E_3: E-3
          E_4: E-4
          E_5: E-5
          E_6: E-6
          E_7: E-7
          E_8: E-8
          E_9: E-9
          E_9_SPECIAL_SENIOR_ENLISTED: E-9 (Special Senior Enlisted)
          O_1_ACADEMY_GRADUATE: O-1 or Service Academy Graduate
          O_2: O-2
          O_3: O-3
          O_4: O-4
          O_5: O-5
          O_6: O-6
          O_7: O-7
          O_8: O-8
          O_9: O-9
          O_10: O-10
          W_1: W-1
          W_2: W-2
          W_3: W-3
          W_4: W-4
          W_5: W-5
          AVIATION_CADET: Aviation Cadet
          CIVILIAN_EMPLOYEE: Civilian Employee
          ACADEMY_CADET: Service Academy Cadet
          MIDSHIPMAN: Midshipman
      Edipi:
        example: 1234567890
        type: string
      PhonePrimary:
        example: 9169876543
        type: string
      PhoneSecondary:
        example: 9169876543
        type: string
        x-nullable: true
      EmailPrimary:
        example: a@b.com
        type: string
      EmailSecondary:
        type: string
        x-nullable: true
      OrdersType:
        type: string
      OrdersNumber:
        type: string
      OrdersDate:
        type: string
        format: date-time
      Address:
        $ref: '#/definitions/Address'
      OriginAddress:
        $ref: '#/definitions/Address'
      DestinationAddress:
        $ref: '#/definitions/Address'
      OriginGbloc:
        type: string
        enum:
          - AGFM
          - APAT
          - BGAC
          - BGNC
          - BKAS
          - CFMQ
          - CLPK
          - CNNQ
          - DMAT
          - GSAT
          - HAFC
          - HBAT
          - JEAT
          - JENQ
          - KKFA
          - LHNQ
          - LKNQ
          - MAPK
          - MAPS
          - MBFL
          - MLNQ
          - XXXX
        x-nullable: true
      DestinationGbloc:
        type: string
        enum:
          - AGFM
          - APAT
          - BGAC
          - BGNC
          - BKAS
          - CFMQ
          - CLPK
          - CNNQ
          - DMAT
          - GSAT
          - HAFC
          - HBAT
          - JEAT
          - JENQ
          - KKFA
          - LHNQ
          - LKNQ
          - MAPK
          - MAPS
          - MBFL
          - MLNQ
          - XXXX
        x-nullable: true
      DepCD:
        description: Department Code
        type: string
        x-nullable: true
      TravelAdvance:
        type: string
        x-nullable: true
      MoveDate:
        type: string
        format: date
        x-nullable: true
      TAC:
        description: Transportation Accounting Code
        type: string
        x-nullable: true
      FiscalYear:
        type: integer
        x-nullable: true
      Appro:
        description: Appropriation
        type: string
        x-nullable: true
      Subhead:
        type: string
        x-nullable: true
      ObjClass:
        type: string
        x-nullable: true
      BCN:
        type: string
        x-nullable: true
      SubAllotCD:
        type: string
        x-nullable: true
      AAA:
        type: string
        x-nullable: true
      TypeCD:
        type: string
        x-nullable: true
      PAA:
        type: string
        x-nullable: true
      CostCD:
        type: string
        x-nullable: true
      DDCD:
        type: string
        x-nullable: true
      ShipmentNum:
        description: Number of shipments
        type: integer
      WeightEstimate:
        description: Total weight estimate
        type: number
        format: double
      TransmitCD:
        description: Transmit Code
        type: string
        x-nullable: true
      DD2278IssueDate:
        description: Counseling Date
        type: string
        format: date
      Miles:
        type: integer
      WeightAuthorized:
        type: number
        format: double
      ShipmentId:
        type: string
        format: uuid
      SCAC:
        example: AGFM
        type: string
        x-nullable: true
      OrderNumber:
        description: not to be confused with Orders Number
        type: string
        example: 030-00362
      LOA:
        type: string
        x-nullable: true
      ShipmentType:
        type: string
      EntitlementWeight:
        type: integer
      NetWeight:
        type: integer
      PBP&E:
        description: Pro Gear
        type: number
        format: double
      PickupDate:
        type: string
        format: date
      SitInDate:
        type: string
        format: date
        x-nullable: true
      SitOutDate:
        type: string
        format: date
        x-nullable: true
      SitType:
        example: Destination
        type: string
        x-nullable: true
      Rate:
        type: number
        format: double
        x-nullable: true
      PaidDate:
        type: string
        format: date
        x-nullable: true
      LinehaulTotal:
        type: number
        format: double
        x-nullable: true
      SitTotal:
        type: number
        format: double
        x-nullable: true
      AccessorialTotal:
        type: number
        format: double
        x-nullable: true
      FuelTotal:
        type: number
        format: double
        x-nullable: true
      OtherTotal:
        type: number
        format: double
        x-nullable: true
      InvoicePaidAmt:
        type: number
        format: double
      TravelType:
        description: Travel Type
        example: Shipment of HHG Permitted
        type: string
      TravelClassCode:
        example: PCS
        type: string
      DeliveryDate:
        type: string
        format: date
      ActualOriginNetWeight:
        type: string
      DestinationReweighNetWeight:
        type: string
      CounseledDate:
        type: string
        format: date
  ListReports:
    type: array
    items:
      $ref: '#/definitions/ListReport'
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
      - instance
responses:
  PermissionDenied:
    description: The request was denied.
    schema:
      $ref: '#/definitions/ClientError'
  ServerError:
    description: An unexpected error has occurred in the server.
    schema:
      $ref: '#/definitions/ClientError'
