name: zap-scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Repository
    steps:
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.12.0
          with:
            target: 'https://office.loadtest.dp3.us/devlocal-auth/login'
